services:
  - type: web
    name: voice-mate-app
    env: node
    plan: free
    region: oregon
    buildCommand: cd dist && npm install --production
    startCommand: cd dist && node index.js
    envVars:
      - key: postgresql://postgres:[YOUR-PASSWORD]@db.iyrsvlmnhqvwnbeifdqi.supabase.co:5432/postgres
        value: postgresql://neondb_owner:npg_UPOIa6vWEU0A@ep-wild-poetry-a5j6rgqh.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: false